namespace UltimateControlsDemo
{
    public partial class LayoutsPage : ContentPage
    {
        public LayoutsPage()
        {
            InitializeComponent(); // Generated by XAML, do not duplicate
            this.FadeTo(1, 500);
        }
    }
}